version: "3"

services:
  db:
    image: postgres:16
    container_name: postgres
    restart: always
    env_file: .db-env
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backtier

  post_manager:
    depends_on:
      db:
        condition: service_healthy
    container_name: post_manager
    restart: always
    env_file:
      - .post_manager-env
    build:
      context: post_manager
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - backtier
      - fronttier

  newsline:
    depends_on:
      - post_manager
    container_name: newsline
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8501/_stcore/health"]
      interval: 15s
      timeout: 5s
      retries: 5
    restart: always
    build:
      context: newsline
      dockerfile: Dockerfile
    develop:
      watch:
        - action: rebuild
          path: ./newsline/pyproject.toml
        - action: rebuild
          path: ./newsline/Dockerfile
        - action: sync
          path: ./newsline
          target: /app
    ports:
      - "8501:8501"
    networks:
      - fronttier

volumes:
  db-data:

networks:
  backtier:
    driver: bridge
  fronttier:
    driver: bridge