version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: local-dev-db-for-testing
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5431:5432"
