"""create author, comment, post tables

Revision ID: f9395e6537e3
Revises: 
Create Date: 2024-01-03 14:03:23.796312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f9395e6537e3"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "authors",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "posts",
        sa.Column("author_id", sa.Uuid(), nullable=False, comment="id автора"),
        sa.Column("topic", sa.Integer(), nullable=False, comment="id темы"),
        sa.Column("content", sa.String(), nullable=False, comment="содержимое"),
        sa.Column(
            "creation_date",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="дата создания",
        ),
        sa.Column(
            "edit_date",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="дата последнего редактирования",
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["authors.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "comments",
        sa.Column("author_id", sa.Uuid(), nullable=False, comment="id автора"),
        sa.Column("post_id", sa.Uuid(), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column(
            "creation_date",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="дата создания",
        ),
        sa.Column(
            "edit_date",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="дата последнего редактирования",
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["authors.id"],
        ),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["posts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("comments")
    op.drop_table("posts")
    op.drop_table("authors")
    # ### end Alembic commands ###
