"""create topics table

Revision ID: af2996b62cc4
Revises: f9395e6537e3
Create Date: 2024-01-03 15:33:38.826187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "af2996b62cc4"
down_revision: Union[str, None] = "f9395e6537e3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "topics",
        sa.Column("name", sa.String(), nullable=False, comment="Названание темы"),
        sa.Column(
            "creation_date",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="дата создания",
        ),
        sa.Column(
            "edit_date",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="дата последнего редактирования",
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "posts", sa.Column("topic_id", sa.Uuid(), nullable=False, comment="id темы")
    )
    op.add_column(
        "posts",
        sa.Column(
            "title",
            sa.String(),
            server_default="Без названия",
            nullable=False,
            comment="Заголовок",
        ),
    )
    op.create_foreign_key(None, "posts", "topics", ["topic_id"], ["id"])
    op.drop_column("posts", "topic")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "posts",
        sa.Column(
            "topic", sa.INTEGER(), autoincrement=False, nullable=False, comment="id темы"
        ),
    )
    op.drop_constraint(None, "posts", type_="foreignkey")
    op.drop_column("posts", "title")
    op.drop_column("posts", "topic_id")
    op.drop_table("topics")
    # ### end Alembic commands ###
