"""correction of a typo in the column description

Revision ID: afab886f9a9f
Revises: 827f86d829de
Create Date: 2024-01-03 17:30:04.374272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "afab886f9a9f"
down_revision: Union[str, None] = "827f86d829de"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "topics",
        "name",
        existing_type=sa.VARCHAR(),
        comment="Название темы",
        existing_comment="Названание темы",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "topics",
        "name",
        existing_type=sa.VARCHAR(),
        comment="Названание темы",
        existing_comment="Название темы",
        existing_nullable=False,
    )
    # ### end Alembic commands ###
