"""add unique constraint for topics and likes tables

Revision ID: e9b326baa673
Revises: 515f1a65cabd
Create Date: 2024-01-09 19:04:50.601097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e9b326baa673"
down_revision: Union[str, None] = "515f1a65cabd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("like_unique", "likes", ["author_id", "post_id"])
    op.create_unique_constraint(None, "topics", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "topics", type_="unique")
    op.drop_constraint("like_unique", "likes", type_="unique")
    # ### end Alembic commands ###
