name: Post manager run tests
run-name: ${{ github.event_name }} to ${{ github.ref_name }} by @${{ github.actor }}
env:
  LINTER_SKIPPED: true
on:
  push:
    branches:
      - post_manager**
      - dev
  pull_request:
    branches:
      - post_manager**
      - dev
jobs:
  lint:
    if: ${{ github.event_name == 'push' }}
    uses: ./.github/workflows/linting.yml

  testing:
    name: Testing
    needs: [ lint ]
    if: ${{ !failure() && !cancelled() && always() }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.9", "3.10", "3.11" ]
    steps:
      -
        name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      -
        name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: false
          virtualenvs-in-project: false
          installer-parallel: true
      -
        name: Get post manager code
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            post_manager
          sparse-checkout-cone-mode: false
      -
        name: Install dependencies
        run: |
          cd post_manager
          poetry install --no-interaction --no-root --no-directory --with dev
      -
        name: Run tests
        run: |
          cd post_manager
          poetry run pytest